
name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --configuration Release --no-build
    
    - name: Publish Windows
      run: dotnet publish src/BBCDisk/BBCDisk.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:Version=${{ steps.get_version.outputs.VERSION }} -o publish/win-x64
    
    - name: Publish macOS
      run: dotnet publish src/BBCDisk/BBCDisk.csproj -c Release -r osx-x64 --self-contained true -p:PublishSingleFile=true -p:Version=${{ steps.get_version.outputs.VERSION }} -o publish/osx-x64
    
    - name: Publish Linux
      run: dotnet publish src/BBCDisk/BBCDisk.csproj -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -p:Version=${{ steps.get_version.outputs.VERSION }} -o publish/linux-x64
    
    - name: Create Windows ZIP
      run: cd publish/win-x64 && zip -r ../../bbc-disk-windows-x64-${{ steps.get_version.outputs.VERSION }}.zip *
    
    - name: Create macOS ZIP
      run: cd publish/osx-x64 && zip -r ../../bbc-disk-macos-x64-${{ steps.get_version.outputs.VERSION }}.zip *
    
    - name: Create Linux ZIP
      run: cd publish/linux-x64 && zip -r ../../bbc-disk-linux-x64-${{ steps.get_version.outputs.VERSION }}.zip *
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bbc-disk-windows-x64-${{ steps.get_version.outputs.VERSION }}.zip
          bbc-disk-macos-x64-${{ steps.get_version.outputs.VERSION }}.zip
          bbc-disk-linux-x64-${{ steps.get_version.outputs.VERSION }}.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}